[package]
name = "ande-rpc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ande-primitives = { workspace = true }
governor = "0.6"
nonzero_ext = "0.3"
thiserror.workspace = true
tracing.workspace = true
