[package]
name = "ande-primitives"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["serde"] }
serde = { workspace = true }
